org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.57-beta

## Mod Properties
mod_id=artronindustries
mod_name=Artron Industries
mod_license=MIT
mod_version=1.0.0
mod_group_id=net.zagdrath.artronindustries
mod_authors=Zagdrath
mod_description=Artron Industries
